### ISSUE TITLE
Dropbox has frozen this app pending review

### ISSUE THREAD

**Issue by jrstrick** [hwittenborn/celeste#110] opened 2023-05-17 17:03 UTC
Error message when trying to connect to dropbox:

This app is unable to link additional users because it has been frozen pending review.  Per Dropbox's website, when you cross over 50 users, you get a two-week warning before they require you to apply for production status. It looks to be largely pro-forma, on first skim.

**Comment by rastarr** [comment] 2023-09-14 03:44
Is there any update on getting Dropbox working? I still get this error about Celeste has been frozen pending review

**Comment by hwittenborn** [comment] 2023-09-14 17:53
I'm working on getting some time set aside to get this worked on @jrstrick @rastarr, see https://github.com/hwittenborn/celeste/issues/76#issuecomment-1719893841 for the current situation.

I just realized this is a duplicate of that issue, so I'll go ahead and close this in favor of that one. I'll post any updates I have on the situation over there.

**Closed by hwittenborn** 2023-09-14 17:53 UTC
