### ISSUE TITLE
Unable to login to dropbox

### ISSUE THREAD

**Issue by Juasmis** [hwittenborn/celeste#97] opened 2023-04-11 19:48 UTC
And this is the follow up to #96, it seems the app is pending review from Dropbox, not sure there is anything that can be done about this but wanted to let you know

![image](https://user-images.githubusercontent.com/48693399/231272726-6b53adef-3e48-470c-be57-a95921064579.png)

**Comment by hwittenborn** [comment] 2023-06-08 08:23
Hey! Sorry for the delayed response, I'm working on about 5 projects right now and I've been going back and forth trying to get them all moving forward, and there's periods like this where development can get slow a bit.

This looks like it's a duplicate of #76 though, so I'm going to go ahead and close this in favor of that.

**Closed** 2023-06-08 08:23 UTC

**Comment by Juasmis** [comment] 2023-06-08 10:21
Oh I did not notice, sorry!
Keep up the good work 💪💪
